from pyunicore.helpers.connection.registry import connect_to_registry
from pyunicore.helpers.connection.registry import connect_to_site_from_registry
from pyunicore.helpers.connection.site import connect_to_site
