name: Mirror to EBRAINS

on:
  push:
    branches: [ dev ]

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: syncmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/pyunicore"
          source_branch: "dev"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/unicore/pyunicore.git"
          destination_branch: "dev"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/pyunicore"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/unicore/pyunicore.git"
          destination_branch: "refs/tags/*"
