# This workflow runs integration tests using
# the unicore-testing-all Docker container

name: Integration tests

on: workflow-dispatch

jobs:
  integration-test:
  
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/unicore-eu/unicore-testing-all:8.3.0
      ports:
        - 8080:8080

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jwt
    - name: Tests
      run: |
        curl -k -u demouser:test123 -H "Accept: application/json" https://localhost:8080/DEMO-SITE/rest/core

